### ISSUE TITLE
Positioning vs. setuptools-py2cfg

### ISSUE THREAD

**Issue by cclauss** [akx/setuppy2cfg#1]
How is this project better than `setuptools-py2cfg`?
What are the reasons to choose one tool over the other?

https://pypi.org/project/setuptools-py2cfg --> https://github.com/gvalkov/setuptools-py2cfg

**Comment by akx** [comment]
Hi there.

No idea, honestly! I wasn't aware of that project when I wrote this tool for my own uses 9 months ago. :)
